### ISSUE TITLE
back quote can't render properly

### ISSUE THREAD

**Issue by IWANABETHATGUY** [Avi-D-coder/FiraCode-italic#2]
In Javascript we use back quote a lot , when i type back quote fira code italic render like this , overlap with semicolon
![image](https://user-images.githubusercontent.com/17974631/68193576-3c458880-ffee-11e9-9af1-1443671a71e9.png)

In Comparison with Fira Code which is expected result
![image](https://user-images.githubusercontent.com/17974631/68193371-f092df00-ffed-11e9-8e07-59e40c3d610b.png)
by the way, you make this awsome font, thank you

**Comment by Avi-D-coder** [comment]
What editor are you using? For me it renders properly.
